//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumasStokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KumasOzellikleri
    {
        public int ID { get; set; }
        public Nullable<int> TopSayisi { get; set; }
        public Nullable<decimal> Metre { get; set; }
        public string Renk { get; set; }
        public Nullable<int> KumasTipiID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Tbl_KumasTipi Tbl_KumasTipi { get; set; }
    }
}
