//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumasStokTakip.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KumasTakipEntities2 : DbContext
    {
        public KumasTakipEntities2()
            : base("name=KumasTakipEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullaniciGiris> KullaniciGiris { get; set; }
        public virtual DbSet<KumasOzellikleri> KumasOzellikleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_KumasTipi> Tbl_KumasTipi { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
    }
}
